tagger:
  - extension: ts
    tag: Ldef Limpls Lrefs Lsyms Ltype Lrn
  - extension: js
    tag: Ldef Limpls Lrefs Lsyms Ltype Lrn
  - extension: go
    tag: Ldef Limpls Lrefs Lsyms Ltype Lrn
  - extension: sql
    tag: sqlf psqlq asqq
  - extension: md
    tag: Font
  - extension: ex
    tag: Ldef Lhov
  - extension: exs
    tag: Ldef Lhov
formatting:
  - extension: go
    command: goimports %f
  - extension: ex
    command: mix format %f
    in_place: true
  - extension: exs
    command: mix format %f
    in_place: true
  - extension: heex
    command: mix format %f
    in_place: true
  - extension: md
    command: prettier --print-width=78 --prose-wrap=always %f
  - extension: ts
    command: prettier --print-width=78 %f
  - extension: svelte
    command: prettier --print-width=78 %f
llm:
  default_provider: ollama
  providers:
    ollama:
      type: ollama
      model: qwen2.5-coder:32b
      params:
        base_url: http://10.0.0.50:11434
