tagger:
  - extension: ts
    tag: sqlf Ldef Limpls Lrefs Lsyms Ltype Lrn
  - extension: js
    tag: sqlf Ldef Limpls Lrefs Lsyms Ltype Lrn
  - extension: go
    tag: sqlf Ldef Limpls Lrefs Lsyms Ltype Lrn
  - extension: sql
    tag: sqlf psqlq asqq
ollama:
  default_model: phi4
  base_url: http://localhost:11434
